# Cannot have power removed
superadmin: Bionicrm
# Must be authed by NickServ
admins:
- lol768
# Channels here will automatically be joined
channels:
- "#lol768fanclub"
channel-commands:
  "#lol768fanclub":
    example: |
      {
        "name": "example",
        "description": "Prints out an example message",
        "usage": "<command>",
        "auth": "PUBLIC",
        "script": "var name = event.getUser().getNick(); // omg JS!\nevent.respond(\"This is an example, \" + name + \".\");"
      }
# "Fax" for LolFax command - Pull Requests welcome!
lolfax:
- "lol768 created politeness"
flip:
  "!": "¡"
  "\"": "„"
  "&": "⅋"
  "'": ","
  "(": ")"
  ".": "˙"
  "3": "Ɛ"
  "4": "ᔭ"
  "6": "9"
  "7": "Ɫ"
  ";": "؛"
  "<": ">"
  "?": "¿"
  "A": "∀"
  "B": "b"
  "C": "Ↄ"
  "D": "◖"
  "E": "Ǝ"
  "F": "Ⅎ"
  "G": "⅁"
  "J": "ſ"
  "K": "⋊"
  "L": "⅂"
  "M": "W"
  "N": "ᴎ"
  "P": "Ԁ"
  "Q": "Ό"
  "R": "ᴚ"
  "T": "⊥"
  "U": "∩"
  "V": "ᴧ"
  "Y": "⅄"
  "[": "]"
  "_": "‾"
  "a": "ɐ"
  "b": "q"
  "c": "ɔ"
  "d": "p"
  "e": "ǝ"
  "f": "ɟ"
  "g": "ƃ"
  "h": "ɥ"
  "i": "ı"
  "j": "ɾ"
  "k": "ʞ"
  "l": "ʃ"
  "m": "ɯ"
  "n": "u"
  "r": "ɹ"
  "t": "ʇ"
  "v": "ʌ"
  "w": "ʍ"
  "y": "ʎ"
  "{": "}"
  "‿": "⁀"
  "⁅": "⁆"
  "∴": "∵"
# YouTube link parsing
youtube:
  enabled: false
  api-key: "api-key-here"
# WolframAlpha queries
wolframalpha:
  enabled: false
  api-key: "api-key-here"
# Define queries
dictionaryapi:
  enabled: false
  api-key: "api-key-here"
weather:
  wunderground:
    # If this is false, OpenWeatherMap will be used instead - requires no API key but is less accurate
    enabled: false
    api-key: "api-key-here"
