# Cannot have power removed
superadmin: Bionicrm
# Must be authed by NickServ
admins:
- lol768
# Channels here will automatically be joined
channels:
- "#lol768fanclub"
channel-commands:
  "#lol768fanclub":
    example: |
      {
        "name": "example",
        "description": "Prints out an example message",
        "usage": "<command>",
        "auth": "PUBLIC",
        "script": "var name = event.getUser().getNick(); // omg JS!\nevent.respond(\"This is an example, \" + name + \".\");"
      }
# "Fax" for LolFax command - Pull Requests welcome!
lolfax:
- "lol768 created politeness"
- "Anyone that doesn't like lol768 is a liar"
- "lol768 loves all"
- "lol768 prefers British spellings"
- "lol768 is OP"
- "lol768 > *"
- "lol768 hates being pinged"
- "tea > *"
- "lol768 > tea > *"
- "lol768 has a love/hate relationship with coffee"
- "lol768 breathes tea"
- "Tea is life"
- "tea > coffee"
- "lol768 is PHP (unless you don't like PHP... in that case lol768 is Java)"
- "If lol768 doesn't know, nobody knows"
- "lol768 created Minecraft"
- "lol768 created the computer"
- "lol768 prefers Linux"
- "lol768 is the real MVP"
- "There was lol768 before light"
- "lol768 likes webdev"
- "lol768 likes Laravel"
- "lol768 likes telling stories"
- "lol768 stories are usually about web security"
- "lol768 points out that there's a cat in a picture of a cat"
- "lol768 created happiness"
- "lol768 cannot lose"
- "lol768 donated his life savings to charity"
- "All occurances of \"god\" in the Bible can be replaced with \"lol768\""
- "lol768 gentrifies neighborhoods by driving through them"
- "lol768 wrote \"London Bridge is Falling Down\""
- "lol768 doesn't live in London; London lives in lol768"
- "lol768 doesn't believe in God because he is God"
- "lol768 doesn't like JavaScript because unlike him, it doesn't haven class(es)"
- "lol768 created the decimal number system"
- "lol768 was able to speak PHP fluently at the age of 2"
- "lol768 stopped coding once; the universe had a kernel panic"
- "lol768 lives in England but that is fine; he absorbs the rain to become stronger and to use stronger-typed languages"
- "lol768's internet connection has a ping latency of -1ms"
- "lol768's broadband never cuts out; the rest of the internet just fails to serve his computer"
- "lol768's laptop has a screen resolution of 8192x4096"
- "RamNode pays lol768 to host his VPS"
- "lol768's laptop has an Intel Core i9 processor"
- "lol768's bathroom is tiled with the motherboards he created from raw atoms"
- "lol768 didn't like the film The Matrix, as he saw Neo as an inaccurate portrayal of himself"
- "lol768 invented the concept of open source"
- "lol768 likes Linux Mint; he created it by compressing and rearranging mint plants into the shape of a DVD"
- "lol768 once entered an incorrect password; the computer quickly apologised as it thought it was at fault"
- "lol768 does not party; lol768 IS the party"
- "lol768 used superpowers to flatten CRTs into LCDs"
- "lol768 can apt-get install packages that don't currently exist; they come into being when he chooses"
- "Sentient life was the result of lol768 messing with AI"
- "Every Wolfram Alpha response is actually lol768 replying with the correct answer"
- "lol768 can break out of an infinity loop"
- "Whenever lol768 uses a random function, it always results in 768"
- "<Chester> lol768 enjoys herding kittens at ten.java"
- "<Chester> lol768 is here to save you."
- "lol768 can spell kernel"
flip:
  "!": "¡"
  "\"": "„"
  "&": "⅋"
  "'": ","
  "(": ")"
  ".": "˙"
  "3": "Ɛ"
  "4": "ᔭ"
  "6": "9"
  "7": "Ɫ"
  ";": "؛"
  "<": ">"
  "?": "¿"
  "A": "∀"
  "B": "b"
  "C": "Ↄ"
  "D": "◖"
  "E": "Ǝ"
  "F": "Ⅎ"
  "G": "⅁"
  "J": "ſ"
  "K": "⋊"
  "L": "⅂"
  "M": "W"
  "N": "ᴎ"
  "P": "Ԁ"
  "Q": "Ό"
  "R": "ᴚ"
  "T": "⊥"
  "U": "∩"
  "V": "ᴧ"
  "Y": "⅄"
  "[": "]"
  "_": "‾"
  "a": "ɐ"
  "b": "q"
  "c": "ɔ"
  "d": "p"
  "e": "ǝ"
  "f": "ɟ"
  "g": "ƃ"
  "h": "ɥ"
  "i": "ı"
  "j": "ɾ"
  "k": "ʞ"
  "l": "ʃ"
  "m": "ɯ"
  "n": "u"
  "r": "ɹ"
  "t": "ʇ"
  "v": "ʌ"
  "w": "ʍ"
  "y": "ʎ"
  "{": "}"
  "‿": "⁀"
  "⁅": "⁆"
  "∴": "∵"
# YouTube link parsing
youtube:
  enabled: false
  api-key: "api-key-here"
# WolframAlpha queries
wolframalpha:
  enabled: false
  api-key: "api-key-here"
# Define queries
dictionaryapi:
  enabled: false
  api-key: "api-key-here"
weather:
  wunderground:
    # If this is false, OpenWeatherMap will be used instead - requires no API key but is less accurate
    enabled: false
    api-key: "api-key-here"
