# Cannot have power removed
superadmin: jkcclemens
# Must be authed by NickServ
admins:
- WizardCM
# Channels here will automatically be joined
channels:
- "#royalbot"
channel-commands:
  "#royalbot":
    example: |
      {
        "name": "example",
        "description": "Prints out an example message",
        "usage": "<command>",
        "auth": "PUBLIC",
        "script": "var name = event.getUser().getNick(); // omg JS!\nevent.respond(\"This is an example, \" + name + \".\");"
      }
# "Fax" for BaxFax command - Pull Requests welcome!
baxfax:
- "mbaxter is not a mother. Not actually."
- "mbaxter once ate twelve gorillas for fun."
- "No one knows the origin of the original mbaxter."
- "TnT cannot harm mbaxter; it is against his Code of Conduct."
- "mbaxter is impervious to fire, but weak against earth."
- "mbaxter's melting point is 8,000 degrees Kelvin."
- "mbaxter goes by mbax or mombaxter."
- "mbaxter cannot be harmed by mere mortals."
- "mbaxter opened the gates to Hell."
- "Those who glimpse the face of mbaxter often die from shock."
- "mbaxter is 25% zinc!"
- "Bonus fact! mbaxter is mbaxter!"
- "mbaxter will frequently abuse Chester."
- "mbaxter once said, \"Meow meow meow! That's what a cat sounds like!\""
- "mbaxter manually delivers each baxfax straight to you!"
- "mbaxter cannot remember who he once was."
- "The light inside mbaxter has gone out."
- "Just kidding. mbaxter's light is still shining!"
- "mbaxter is opinionated."
- "mbaxter is like hawkfalcon, only better."
- "mbaxter made Minecraft."
- "mbaxter made the earth."
- "mbaxter made Bukkit."
- "mbaxter invented light."
- "mbaxter is master race."
- "mbaxter cannot be comprehended by us puny mortals."
- "mbaxter takes what he wants."
- "mbaxter made water."
- "mbaxter often kills baby whales just to show them that he's in control."
- "mbaxter says, \"Take this. It's dangerous to go alone.\""
- "mbaxter gives good staff members cookies."
- "mbaxter doesn't know how to not know."
- "mbaxter is the epitome of cool."
- "mbaxter is. You should be greatful."
- "Remember mbaxter? He's a cool guy."
- "mbaxter hates baxfax... Just kidding!"
- "mbaxter is the heart and soul of the universe."
- "mbaxter is turning 63 this year. Congratulations!"
- "mbaxter pushes straight to repositories. No need for pull requests."
- "mbaxter is not a potato."
- "mbaxter's best friend is jkcclemens. For real!"
- "/whois mbaxter. Go ahead, try it out."
- "mbaxter is not of this world."
- "mbaxter's favorite video game is \"MBAXTER: Anthology\""
- "mbaxter loves all music, especially rap and hip-hop."
- "All baxfax are guaranteed true or your money back!"
- "mbaxter is the true path."
- "mbaxter is love."
- "mbaxter explodes things he disagrees with."
- "mbaxter > EvilSeph"
- "mbaxter loves all and hates none (mostly)."
- "mbaxter is your lord and ruler."
- "mbaxter is not a mother. Not yet."
- "mbaxter is a virgin and has given birth to seven donkeys."
- "mbaxter is a pimp."
- "mbaxter is a player."
- "mbaxter wakes up and slaughters his enemies."
- "mbaxter: Woohoo!"
- "mbaxter invented sound."
- "mbaxter created YouTube."
- "mbaxter owns Google."
- "mbaxter is the corporation."
- "mbaxter is the revolution."
- "mbaxter loves being pinged several times!"
- "mbaxter regrets his decisions."
- "mbaxter's favorite other game is Sonic the Hedgehog!"
- "mbaxter runs Bukkit internally."
- "mbaxter requires no maintenance. Plug him in and leave him!"
- "mbaxter doesn't need to sleep."
- "mbaxter exists to rule."
- "mbaxter will judge your code; beware."
- "mbaxter mbaxter mbaxter!"
- "Cats have a tendency to land on their feet!"
- "Cats like mbaxter."
- "mbaxter likes cats."
- "Dogs aren't quite like cats."
- "Kitteh is the preferred spelling of kitten for mbaxter."
- "mbaxter once said, \"Where are my oven mitts?\""
- "mbaxter didn't say a lot of things."
- "mbaxter's brother is tbaxter."
- "Baxfax are 100% free because of mbaxter's hard labor."
- "mbaxter prefers British spellings over Americanized spellings."
- "mbaxter questions the validity of some of these fax."
- "mbaxter can recite the Bukkit JavaDocs by heart."
- "mbaxter likes the term \"javaducks.\""
- "mbaxter made the computer you're using."
- "mbaxter made you."
- "mbaxter is the moon and the sun and the stars."
- "mbaxter does not code; code mbaxters."
- "mbaxter poops out bars of gold."
- "Beware impostors! Official baxfax only come from approved sources."
- "The average kitten is VERY adorable."
- "The speed of mbaxter is 3*10^8."
- "mbaxter can punch so hard the mass of anything he punches gets so concentrated a black hole is formed."
- "mbaxter can escape an event horizon."
- "Ads are too scared to show on pages mbaxter loads."
- "mbaxter banned this bot. :("
- "mbaxter enjoys being pinged by these facts."
- "mbaxter is life."
- "mbaxter is literally Bukkit 1.7."
flip:
  "!": "¡"
  "\"": "„"
  "&": "⅋"
  "'": ","
  "(": ")"
  ".": "˙"
  "3": "Ɛ"
  "4": "ᔭ"
  "6": "9"
  "7": "Ɫ"
  ";": "؛"
  "<": ">"
  "?": "¿"
  "A": "∀"
  "B": "b"
  "C": "Ↄ"
  "D": "◖"
  "E": "Ǝ"
  "F": "Ⅎ"
  "G": "⅁"
  "J": "ſ"
  "K": "⋊"
  "L": "⅂"
  "M": "W"
  "N": "ᴎ"
  "P": "Ԁ"
  "Q": "Ό"
  "R": "ᴚ"
  "T": "⊥"
  "U": "∩"
  "V": "ᴧ"
  "Y": "⅄"
  "[": "]"
  "_": "‾"
  "a": "ɐ"
  "b": "q"
  "c": "ɔ"
  "d": "p"
  "e": "ǝ"
  "f": "ɟ"
  "g": "ƃ"
  "h": "ɥ"
  "i": "ı"
  "j": "ɾ"
  "k": "ʞ"
  "l": "ʃ"
  "m": "ɯ"
  "n": "u"
  "r": "ɹ"
  "t": "ʇ"
  "v": "ʌ"
  "w": "ʍ"
  "y": "ʎ"
  "{": "}"
  "‿": "⁀"
  "⁅": "⁆"
  "∴": "∵"
# YouTube link parsing
youtube:
  enabled: false
  api-key: "api-key-here"
# WolframAlpha queries
wolframalpha:
  enabled: false
  api-key: "api-key-here"
# Define queries
dictionaryapi:
  enabled: false
  api-key: "api-key-here"
weather:
  wunderground:
    # If this is false, OpenWeatherMap will be used instead - requires no API key but is less accurate
    enabled: false
    api-key: "api-key-here"
